### ISSUE TITLE
module_not_found error @stacks/cli

### ISSUE THREAD

**Issue by theo-learner** [stx-labs/stacks.js#1009]
After I updated and installed @stacks/cli to 1.4.1. The module_not_found error is remaining. I'm using node v14.16.1.

Error log is here:
```bash
Error: Cannot find module '/home/bhlee/share/tutorial/manage_accounts/node_modules/@stacks/cli/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/bhlee/share/tutorial/manage_accounts/generate_account.js:14:30)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/bhlee/share/tutorial/manage_accounts/node_modules/@stacks/cli/package.json',
  requestPath: '@stacks/cli'
}
```

**Comment by theo-learner** [comment]
Please I'm waiting any update, comment, information for solving the problem. I'm trying to use Node 15.x but I cannot resolve it.

**Comment by theo-learner** [comment]
Is there a temporary solution?

**Comment by wileyj** [comment]
@markmhx

**Comment by markmhendrickson** [comment]
cc @agraebe

**Comment by theo-learner** [comment]
Any comments or solutions?

**Comment by zone117x** [comment]
Can you see if this is fixed in [`@stacks/cli@1.5.0-alpha.1`](https://www.npmjs.com/package/@stacks/cli/v/1.5.0-alpha.1)?

**Comment by theo-learner** [comment]
@zone117x Now runtime error is gone after updated to `@stacks/cli@1.5.0-alpha.1`. But when I execute short code using node v14.16.1, CLI help menu is appeared. The below are my short code and terminal log. Please let me know how to use API in @stacks/cli (e.g., `decodePrivateKey`, `getBackupPhrase`, ...) . Thanks.

short code:
```javascript
const {
    makeRandomPrivKey,
    privateKeyToString,
    getAddressFromPrivateKey,
    TransactionVersion, ChainID, createStacksPrivateKey
} = require('@stacks/transactions');
const { generateMnemonicRootKeychain, deriveRootKeychainFromMnemonic, encryptMnemonicFormatted, encrypt, decrypt, deriveStxAddressChain } = require('@stacks/keychain');
const { decodePrivateKey } = require('@stacks/cli');
const util = require('util');

const MNEMONIC_ENTROPY = 256;

async function genereateKey() {

    const key = await generateMnemonicRootKeychain(MNEMONIC_ENTROPY);
    console.log("keychain: " + util.inspect(key, false, 3, true));

    console.log("Mnemonic: " + util.inspect(key.plaintextMnemonic, false, 3, true));

    console.log("privatekey: " + util.inspect(key.rootNode.privateKey, false, 3, true));

    const privateKey = createStacksPrivateKey(key.rootNode.privateKey);
    console.log("privatekey: " + util.inspect(privateKey, false, 3, true));

    const decodeKey = decodePrivateKey(privateKeyToString(privateKey))
    console.log("decodeKey: " + util.inspect(decodeKey, false, 3, true));
}
generateKey();
```

Teminal log:
```bash
node test.js 
No command given
Usage: /home/bhlee/tutorial/manage_accounts/test.js [options] command [command arguments]
Options can be:
    -c                  Path to a config file (defaults to
                        ~/.blockstack-cli.conf)

    -d                  Print verbose debugging output

    -e                  Estimate the BTC cost of an transaction (in satoshis).
                        Do not generate or send any transactions.

    -m MAGIC_BYTES      Use an alternative magic byte string instead of "id".

    -t                  Use the public testnet instead of mainnet.

    -i                  Use integration test framework instead of mainnet.

    -U                  Unsafe mode.  No safety checks will be performed.

    -x                  Do not broadcast a transaction.  Only generate and
                        print them to stdout.

    -B BURN_ADDR        Use the given namespace burn address instead of the one
                        obtained from the Blockstack network (DANGEROUS)

    -D DENOMINATION     Denominate the price to pay in the given units
                        (DANGEROUS)

    -C CONSENSUS_HASH   Use the given consensus hash instead of one obtained
                        from the network

    -F FEE_RATE         Use the given transaction fee rate instead of the one
                        obtained from the Bitcoin network

    -G GRACE_PERIOD     Number of blocks in which a name can be renewed after it
                        expires (DANGEROUS)

    -H URL              Use an alternative Blockstack Core API endpoint.

    -I URL              Use an alternative Blockstack Core Indexer endpoint.

    -M MAX_INDEX        Maximum keychain index to use when searching for an identity address
                        (default is 256).

    -N PAY2NS_PERIOD    Number of blocks in which a namespace receives the registration
                        and renewal fees after it is created (DANGEROUS)

    -P PRICE            Use the given price to pay for names or namespaces
                        (DANGEROUS)

    -T URL              Use an alternative Blockstack transaction broadcaster.
    
    -X URL              Use an alternative UTXO service endpoint.

    -u USERNAME         A username to be passed to bitcoind RPC endpoints

    -p PASSWORD         A password to be passed to bitcoind RPC endpoints

All commands (run '/home/bhlee/tutorial/manage_accounts/generate_account-test.js help COMMAND' for details):
  Account Management: 
    balance, can_stack, call_contract_func, call_read_only_contract_func
    convert_address, deploy_contract, get_account_history
    get_account_at, send_btc, send_tokens, stack, stacking_status

  Authentication: 
    authenticator

  Blockstack ID Management: 
    renew, register, register_addr, register_subdomain, revoke, transfer
    tx_preorder, tx_register, update

  CLI: 
    docs, help

  DID: 
    get_did_configuration

  Gaia: 
    gaia_dump_bucket, gaia_getfile, gaia_putfile, gaia_deletefile
    gaia_listfiles, gaia_restore_bucket, gaia_sethub

  Key Management: 
    decrypt_keychain, encrypt_keychain, faucet, get_address, get_app_keys
    get_owner_keys, get_payment_key, get_stacks_wallet_key
    make_keychain

  Namespace Operations: 
    get_namespace_blockchain_record, name_import, namespace_preorder
    namespace_reveal, namespace_ready, price_namespace

  Peer Services: 
    announce, get_confirmations, get_zonefile, make_zonefile
    zonefile_push

  Profiles: 
    profile_sign, profile_store, profile_verify

  Querying Blockstack IDs: 
    get_blockchain_record, get_blockchain_history, lookup, names, price
    whois
```

**Comment by zone117x** [comment]
The `@stacks/cli` is a CLI utility, intended for usage on the command line. See usage docs from the readme: https://docs.stacks.co/references/stacks-cli

Using it as a library dependency is not supported and will probably never be.
